# Standards: 0.11
---

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)

- name: 1.1.7 - Ensure separate partition exists for /var/tmp (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "{{item.opts}}"
  with_items:
    - { mountpoint: "{{cis_partition_mnt_val_var_tmp}}", device: "{{cis_partition_dev_val_var_tmp}}", fstype: "{{cis_partition_fs_val_var_tmp}}", opts: "{{cis_partition_opts_val_var_tmp}}" }
  tags:
      - level-1
      - section-1
      - "1.1.7"
      - scored
