# Standards: 0.11
---

# 1.1.6 Ensure separate partition exists for /var (Scored)

- name: 1.1.6 - Ensure separate partition exists for /var (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
  with_items:
    - { mountpoint: "{{cis_partition_mnt_val_var}}", device: "{{cis_partition_dev_val_var}}", fstype: "{{cis_partition_fs_val_var}}" }
  tags:
      - level-1
      - section-1
      - "1.1.6"
      - scored
