# Standards: 0.11
---

# 3.3.3 Ensure /etc/hosts.deny is configured

- name: 3.3.3 - Ensure /etc/hosts.deny is configured
  copy:
    path: "/etc/hosts.deny"
    content: "ALL: ALL\n"
  tags:
    - level-1
    - section-3
    - "3.3.3"
    - scored
