# Standards: 0.11
---

# 3.3.2 Ensure /etc/hosts.allow is configured

- name: "3.3.2 - Ensure /etc/hosts.allow is configured (add list of allowed IP Range, if provided)"
  copy:
    path: "/etc/hosts.allow"
    content: "ALL: {{ cis_hosts_allowed_ip_range }}\n"
  when: cis_hosts_allowed_ip_range is defined and cis_hosts_allowed_ip_range != ""
  tags:
    - level-1
    - section-3
    - "3.3.2"
    - scored

- name: "3.3.2 - Ensure /etc/hosts.allow is configured (Empty the list, if no IP Range provided)"
  copy:
    path: "/etc/hosts.allow"
    content: ""
  when: cis_hosts_allowed_ip_range is not defined or cis_hosts_allowed_ip_range == ""
  tags:
    - level-1
    - section-3
    - "3.3.2"
    - scored
